package com.example.app.data.model

/**
 * In-memory data classes for AI-generated Activity and Sets.
 * These are not Room entities - they represent the raw AI output before
 * being persisted to the database.
 */

/**
 * Complete AI-generated activity data including activity metadata and all sets.
 */
data class AiGeneratedActivity(
    val activity: AiActivityInfo,
    val sets: List<AiGeneratedSet>
)

/**
 * Represents a similarity match between a generated title and an existing one.
 */
data class TitleSimilarity(
    val generatedTitle: String,
    val similarToExisting: String,
    val reason: String,
    val alternateTitle: String = ""
)

/**
 * Activity metadata generated by AI.
 */
data class AiActivityInfo(
    val title: String,
    val description: String,
    val titleSimilarity: TitleSimilarity? = null
)

/**
 * A single set with its metadata and word configurations.
 */
data class AiGeneratedSet(
    val title: String,
    val description: String,
    val words: List<AiWordConfig>,
    val titleSimilarity: TitleSimilarity? = null
)

/**
 * Word configuration for a set, including the word and its practice mode.
 */
data class AiWordConfig(
    val word: String,
    val configurationType: String,  // "fill in the blanks", "name the picture", "write the word"
    val selectedLetterIndex: Int = 0  // Only used for "fill in the blanks"
)

/**
 * Sealed class representing the result of AI generation.
 */
sealed class AiGenerationResult {
    data class Success(val data: AiGeneratedActivity) : AiGenerationResult()
    data class Error(val message: String, val canRetry: Boolean = true) : AiGenerationResult()
    data class InsufficientWords(
        val pattern: String,
        val matchingWords: List<String>,
        val needed: Int = 3,
        val originalPrompt: String = ""
    ) : AiGenerationResult()
}
